### ISSUE TITLE
TNT machines deadlock the client

### ISSUE THREAD

**Issue by robot4jarvis** [jellysquid3/lithium-fabric#202]
### Reproduction Step
1. Start a redstone machine that generates TNT continuously (with one to two TNT at a time it's enough).
2. Wait for some seconds or minutes.
3. The game crashes

### Crash Report File
No crash report was generated.
### Additional Information
It has happened many times.

**Comment by robot4jarvis** [comment]
Do I post the issue on the Phosphor GitHub page?

**Comment by 2No2Name** [comment]
Yes

**Comment by Kroppeb** [comment]
AFAIK, jelly can move the issue.
